### ISSUE TITLE
instanceid from activity

### ISSUE THREAD

**Issue by mizerlou** [Azure/azure-functions-durable-js#209]
how do i access the orchestrators instanceID from within an activity function? 

i'm using javascript.

**Comment by davidmrdavid** [comment]
Hi @mizerlou, 

Thanks for reaching out! The easiest approach would be to pass it as an argument to the activity function. I suggest looking at the orchestrator [here ](https://github.com/Azure/azure-functions-durable-js/blob/dev/samples/E1_HelloSequence/index.js)and the activity [here ](https://github.com/Azure/azure-functions-durable-js/blob/dev/samples/E1_SayHello/index.js) for an example on how to pass arguments to activities. Then, assuming you are writing the orchestrator, instead of passing a literal string to the activity, you could pass `context.df.instanceId`.

Does that fit your scenario? Please let us know! @ConnorMcMahon , I don't think an activity could determine its calling orchestrator otherwise, right?

⚡ ⚡

**Comment by mizerlou** [comment]
@davidmrdavid thanks.  got it.
