### ISSUE TITLE
Number written as string treat as number when call callActivity, so large number will be rounded

### ISSUE THREAD

**Issue by yamachu** [Azure/azure-functions-durable-js#215]
**Describe the bug**

The size of numbers that can be handled by the JavaScript number type is limited.
We sometimes treat large-number as BigInt or string for avoiding that limitation.

That large number was treated as number when I used stringified number as `callActivity`' s parameter.

**Investigative information**

- Durable Functions extension version: 
- durable-functions npm module version: 1.4.3
- Language (JavaScript/TypeScript) and version: JavaScript
- Node.js version: 12

***If deployed to Azure App Service***

- Timeframe issue observed:
- Function App name: 
- Function name(s):
- Region: japan-east
- Orchestration instance ID(s): 

**To Reproduce**

See repro repo
https://github.com/yamachu/repro-durable-functions-js-stringify-large-number

1. request [DurableFunctionsHttpStart](https://github.com/yamachu/repro-durable-functions-js-stringify-large-number/tree/master/DurableFunctionsHttpStart) with big_id parameter
2. see logs

https://github.com/yamachu/repro-durable-functions-js-stringify-large-number/blob/master/logs/view-azure-portal-logstream-curl-big_id-12345678901234567890.txt

This log was logged at Azure Portal LogStream.

**Expected behavior**

If `callActivity("activityName", "12345678901234567890")`, 
we got input "12345678901234567890" as string in "activityName" activity.

**Actual behavior**

If `callActivity("activityName", "12345678901234567890")`, 
we got input 12345678901234567000 as number in "activityName" activity.

**Known workarounds**

Add some characters "@", "n" or .... to stringified number, and remove these characters in activity.

**Additional context**

- Development environment (ex. Visual Studio): Visual Studio Code Insiders
- Links to source: https://github.com/yamachu/repro-durable-functions-js-stringify-large-number
- Additional bindings used
- Function invocation IDs

**Comment by davidmrdavid** [comment]
Hi @yamachu ,

Thank you so much for reaching out! Indeed, you seem to have triggered a bug that's actively being discussed with the team at large. In short, somewhere in our pipeline, your string is getting _interpreted_ as a number and therefore changing its precision. We have a similar problem [here](https://github.com/Azure/azure-functions-durable-extension/issues/1476) but instead of interpreting string-represented numbers, its with interpreting string-represented `Date` objects.

We have a potential mitigation [here](https://github.com/Azure/azure-functions-durable-js/pull/217) but we suspect we can develop a fix that works for all Durable PLs instead of one for just JavaScript. So we'll be waiting a bit to give time to investigate if that's possible. I suspect we should have an answer in a few weeks, and that a fix should be released with an upcoming release of  the JavaScript SDK.

In the meantime, the mitigation would indeed be as you suggest, to add non-numerical characters to the input. That should bypass the interpretation of the string as numeric. We're sorry you're dealing with this, but note that this issue is very high priority for us at the moment. We'll get back to you soon!

⚡ ⚡

**Comment by yamachu** [comment]
Thanks @davidmrdavid 

In my investigation, I figured out this issue was not only durable-functions but also Azure functions.
The problem seemed to be that the given values were being applied to JSON.parse too much...

In locally I avoided this issue by applying [this change](https://github.com/Azure/azure-functions-nodejs-worker/pull/336 ) .

However, this change did not solve the `Date` type problem.
This problem seems to be happening around rpc conversions.

**Comment by davidmrdavid** [comment]
Thank you so much for diving into this as well @yamachu . I've responded to your PR in its corresponding thread. Let's continue our conversation in there :)

**Comment by davidmrdavid** [comment]
Hi @yamachu ,

I _just_ made a release which should address this problem. Do you mind installing the latest release (1.4.4) and letting me know if it worked for you! Thanks :) 

⚡ ⚡

**Comment by yamachu** [comment]
Hi @davidmrdavid
Thanks for letting me know.

I tried latest release in my project.
That's great! The issues I was facing have been resolved :)

Also no more implicit conversions of `"{}"`, `"[]"`, `"null"`, etc., which I think is good.

**Comment by davidmrdavid** [comment]
Awesome! I'll close this ticket for now then :) Thanks for reaching out and for your PR!!

⚡ ⚡
