### ISSUE TITLE
df.Orchestrator - Async Generator Function support

### ISSUE THREAD

**Issue by lee-leonardo** [Azure/azure-functions-durable-js#218]
More of a feature request whilst developing for PWABuilder's api v2 which uses Azure functions and azure resources. Essentially it is an open source Microsoft  project that features an api and tooling to help create PWAs.

Essentially the problem is that Azure Client libraries such as the Azure Blob Storage Client API library makes use of a lot of async functions, which cannot be called directly within the space of a current Durable Function Orchestrator primarily due to the Orchestrator being a synchronous generator function. The tweak to it being compatible with Async Generator functions would solve this issue.

The example I am listing below can be done with chaining, and hence we are not blocked, but it would be quite convenient if we were able to do async operations within the generator. It would save us creating a function call just to retrieve the async information and remove the need for a sub-orchestrator and make the durable function framework more compatible with some of the other azure resources available.

## Use case

Our use case is using blob storage as a temporary storage point for a collection of images that will then need to be scanned quickly to generate the missing images.

## Chaining

- Separate activity to query blob storage and grab the images that need to be generated.
- Calls a sub-orchestrator to fan out the image calls to copy and resize the largest image.
- Zipping and etc (not relevant)

### Chaining Code
```typescript
const orchestrator = df.orchestrator(function* (context, clientData) {
  // to get information from azure client libraries
  const missingImageList = yield context.df.callActivity("GetMissingImages", clientData);

  // sub-orchestrator
  const responses = yield context.df.callActivity("GenerateMissingImagesSubOrchestrator", clientData, missingImageList);
  return yield context.df.callActivity("getZip", clientData);
}
```

### Async Operator

- Queries inside the orchestrator for the images and then fans out from this context the generate activities. 2 less functions to manage

```typescript
const orchestrator = df.orchestrator(async function* (context, clientData) {
  const serviceClient = BlobServiceClient.fromConnectionString();
  /* ... subsequent code in missingImageList (mostly async calls).
     ...
     results in missingImageList
  */
  const missingImageListActivties = missingImageList
            .filter(image => /* check set of image sizes */)
            .map(context.df.callActivity("ResizeImage", /* you get the idea */));
  const responses = yield context.df.Task.all(missingImageListActivties);
  return yield context.df.callActivity("getZip", clientData);
}
```

**Comment by davidmrdavid** [comment]
Hi @lee-leonardo ,

Thank you for the feature request, we're always excited about ways to extend and improve the programming model :) .
I'm not entirely sure I understand the use case, but your description immediately makes me think of the `callHttp` Durable API, which allows you to make async-http requests inside an orchestrator. Does that address your scenario, or does it not? If not, could you tell us why?

**Call HTTP Documentation:** https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-features?tabs=javascript#consuming-http-apis

**Comment by lee-leonardo** [comment]
@davidmrdavid That looks awesome! However it doesn't help with the library I am referring to :( . We can call Azure Storage via HTTP, but we are currently using the convenient mapping and api of [@azure/azure-storage](https://www.npmjs.com/package/azure-storage)

I'm able to push our code for you to view:

### Code we wish to put in the orchestrator
https://github.com/pwa-builder/pwabuilder-api-v2/blob/web_platform/ReadContainer/index.ts#L42-L47

### Orchestrator
https://github.com/pwa-builder/pwabuilder-api-v2/blob/web_platform/PlatformBuildOrchestrator/index.ts#L34-L39

Edit to above as well, we do not need a sub-orchestrator as we can fan out after making the initial call, so it'll just save us one call.
 Let me know if you need more information!

**Comment by davidmrdavid** [comment]
Thanks for the example, @lee-leonardo, I believe I understand your request now! So, you want the orchestrator to be an async generator function: that would enable you to `await` on arbitrary async library-calls, like the one you provided for azure-storage, while in the orchestrator body itself.

A few thoughts on that.

(1) _If we were to implement this..._
I suspect we could implement it as syntactic sugar or through some minimal annotations. To minimize changes to our backend, we could generate an implicit activity call for you when we detect an awaited a non-durable API call. So I suspect this is possible.

(2) _However, there may be a good reason why this isn't implemented yet_

I'm concerned about whether this would complicate the Durable Functions programming model, which currently cleanly delineates the roles of activities and orchestrators. In essence, activities encapsulate non-determinism and the act of explicitly encapsulating foreign / non-durable API calls in activities serves to communicate that they are not guaranteed to be replay-safe, and so they do not belong in the orchestrator body, because that needs to be replay-safe. Does that make sense? A nice side effect of this is also that orchestrators code is often quite predictable: just a handful of durable-API calls, ideally following one of the Durable Patterns.

Now, all that being said, and assuming my concerns are well-founded, there may still be room for _inlined_ activity functions, which would free you from managing a separate activity definition. Perhaps it would work via an Activity constructor that accepts an anonymous function as argument, and the input to it as another.

_So, where you currently have..._

```javascript
const missingImageList = yield context.df.callActivity("GetMissingImages", clientData);
```

_we could instead enable you to write..._

```javascript
const missingImageList = yield context.df.callActivityInlined(
    function() {
        // stuff ...
       // the code you wanted to inline, a call to the azure-storage node API
       for await (const blob of containerClient.listBlobsFlat({
           includeTags: true,
          includeMetadata: true,
        })) {
         output.contents.push(blob);
       }

       output.success = true;
       } catch (e) {
          context.log(e);
          output.error = ExceptionOf(ExceptionType.BLOB_READ_FAILURE, e);
        }

       return output;
        };  
    }, 
    clientData);
```

Now this still runs the risk of
(1) making orchestrator code more cluttered with a mix of inline and non-inlined activities, making it harder to read
(2) the anonymous function may make things harder to debug, as we wouldn't necessarily be able to give you the name of the activity that failed. Although I can imagine ways to get around that too.

But, by forcing users to still encapsulate this work inside an activity constructor, at least we preserve the act of communicating the Durable replayability constraints.

I'm personally leaning towards keeping this in the backburner for now, as I'm not seeing an elegant way to incorporate this in the programming model without these cluttering effects. Still, I want to loop @cgillum and @anthonychu in case they have other thoughts :) 

⚡ ⚡

**Comment by lee-leonardo** [comment]
Ah gotcha! The delineated role between orchestrator and activity makes total sense, encapsulating foreign code, even a Microsoft service, definitely will allow for a more predictable performance. Also the notion of functions being replayable seems very beneficial in regards to debugging :).

Async generators are definitely a nice to have in this situation, but not needed with the design pattern set by the framework. Thanks for humoring me!
