### ISSUE TITLE
context.df.task.any ignores timeout when used with callSubOrchestrator

### ISSUE THREAD

**Issue by Jonz** [Azure/azure-functions-durable-js#234]
**Describe the bug**
When using the pattern described [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-timers?tabs=javascript) with callSubOrchestrator the context.df.Task.any appears to wait for the suborchestration to complete, rather than timeout. I'm not sure whether this is by design or a bug. 

The reasoning behind this approach is to create a fire-and-forget if a task takes more than n seconds, not waiting for the output. I also need to cater for scenarios where I need to delay a suborchestrator execution, and not wait for the output. There's probably a better way to achieve this that I'm missing!

I've created a simple function app to illustrate the behaviour, essentially:

ParentOrchestrator has two tasks:

1. 5 second Timer.
2. callSubOrchestrator.

SubOrchestrator has two tasks:

1. 60 second Timer.
2. call Hello Activity.

**Investigative information**
- Durable Functions extension version:
- durable-functions npm module version: 1.4.4
- Language: Javascript
- Node.js version: 10.16.3

**To Reproduce**
1. Clone https://github.com/Jonz/durablesuborchestratortest
2. Trigger with GET to http://localhost:7074/api/orchestrators/ParentOrchestrator

**Expected behavior**
Parent Orchestrator function returns after 5 seconds, with success = false - i.e. Timer wins race condition and continues.

**Actual behavior**
Parent Orchestrator function returns after ~60 seconds with success = false - i.e. it seems to wait for the inner suborchestration to end.

**Comment by davidmrdavid** [comment]
Hi @Jonz,

Thanks you for reaching out and thank you for the reproducer! I was able to reproduce this behavior and, by comparing against the .NET implementation, I can confirm this is not the expected behavior: your orchestrator **should not** wait for the activity to complete if the timer fires first.

This is a pretty big bug so I'll be prioritizing it for our next release. I should be able to provide an ETA in the coming days. I'll update this thread by then!

⚡ ⚡

**Comment by davidmrdavid** [comment]
Hi @Jonz, I took another look at this issue. After reviewing it with the rest of the team, we determined that this behavior is **by design** and that I was wrong when I originally said that C# had a different behavior. Sorry for the confusion! Let's take a step back and re-establish the new context 😄 .

So, this behaviour is **by design**. Currently, an orchestrator's status is complete only when
(1) It has no remaining "Open Tasks", that is, no scheduled tasks still incomplete
and
(2) The orchestrator has returned.

You can see this behaviour implemented here: https://github.com/Azure/durabletask/blob/075b2ef8ca173203a7e9777a7cc846c44224233b/src/DurableTask.Core/TaskOrchestrationExecutor.cs#L86-L112

Now I do realize that this is a bit counter-intuitive, so we are considering changing this in the future, but we first would need to investigate if doing so would bring unwanted consequences. So, for the time being, it will most likely stay as-is.

So now the question is whether or not this affects the workflow you were trying to implement. Is it **necessary** that the orchestrator get marked as completed for your "fire and forget" scenario? Also, "fire and forget" is a concept we support in [Durable Entities](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp#access-entities)'s "signalEntity" API so perhaps that's worth looking into as well :)

Please let me know of any concerns or limitations and I'll be happy to help you come up with a solution and take on any feedback for future releases! Thanks!  ⚡ ⚡

**Comment by davidmrdavid** [comment]
Also filed an [issue](https://github.com/Azure/azure-functions-durable-extension/issues/1665) to document this :)

**Comment by Jonz** [comment]
Hi @davidmrdavid, 

Thanks for looking into this, and no problem :) I had a play with a couple of solutions for my scenario:

1. Create a new (separate) orchestration instance via an http call - context.df.callHttp.
2. Put the fire-and-forget tasks into the servicebus queue (already part of the app), which then trigger a processing function.

The latter allows me to schedule (for my delay scenario) so all good there, but I'll take a read of the Durable Entity signalEntity API to see if that's more suitable :)
