### ISSUE TITLE
Return object from async activity function

### ISSUE THREAD

**Issue by nafis00141** [Azure/azure-functions-durable-js#25]
In an activity function we return something by doing

`context.done(null, object);`

to the durable function where `object` is my target object to sent.

but when i make my activity function async, i can not use `context.done`

without context.done how can i send my desired object from activity function to the orchestration?

**Comment by kashimiz** [comment]
Async JavaScript functions should use the `return` syntax rather than `context.done` ([documentation here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#outputs)) This holds true for activity functions as well, so you should just need to `return object;`

Note: the linked documentation is written with explicit output bindings in mind but the `activityTrigger` binding can also handle return values.
