### ISSUE TITLE
Func App is not using the storage account set on host.json

### ISSUE THREAD

**Issue by vany0114** [Azure/azure-functions-durable-js#335]
**Describe the bug**
I'm using a NodeJS function app where I have an orchestrator (used for instantiating kind of long-running timers), and an activity function. I'm using a different storage account for the durable tasks stuff by specifying the connection string in the `host.json` file. However it's not working, it is using the default storage account tied to the func app itself. I'm not sure what's going on because it was working fine until last week and nothing have changed, now it seems the timers are not event getting triggered.

**Investigative information**

- Durable Functions extension version: [1.*, 2.8.5)
- durable-functions npm module version: 1.5.4
- Language (JavaScript/TypeScript) and version: TS 4.4.4
- Node.js version: 14

***If deployed to Azure App Service***

- Timeframe issue observed: 30/03/2022 - now
- Function App name: orders-orchestrators
- Function name(s): timingOrchestrator
- Region: West US

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

**Expected behavior**
To use the storage account that I set in the `host.json` for all the durable tasks stuff + timers being triggered once they elapsed.

**Actual behavior**
Using the func app storage account for durable tasks stuff + timers are not being triggered once they elapsed.

**Known workarounds**
I already tried re-provisioning the storage account that I used for durable tasks as well as re-provisioning the func app but didn't work.

host.json
```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "storageProvider": {
        "useLegacyPartitionManagement": false,
        "connectionStringName": "TIMING_ORCHESTRATOR_DUEABLETASK_STORAGE_CONNECTIONSTRING"
      },
      "useGracefulShutdown": true
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.8.5)"
  }
}

```

**Edit:** the same func app is working fine in our development environment FWIW.

**Comment by vany0114** [comment]
Any update on this?

**Comment by vany0114** [comment]
@cgillum any update? 🙏

**Comment by cgillum** [comment]
Hi @vany0114 sorry that this issue seems to have been missed!

I just now took a look at your app (thanks for providing the info) and it looks like you're using a really old version of the Durable Functions extension (v1.8.7). I'm guessing this has to do with the bundles version you have configured in host.json. I think this explains the problem, actually: the host.json you shared above uses the schema that we have for Durable Functions v2.x and greater. Since you're on Durable Functions v1.8.7, there's actually a schema mismatch and I think the Durable extension is silently falling back to using AzureWebJobsStorage as the default storage account.

I think you have a couple options to fix this:

1. Use a newer version of extension bundles (preferably the latest, version 3.x bundles). That will ensure you're configured with the latest Durable Functions extension which matches the host.json schema above. If you can't do this, then your other option is to...
2. Change your host.json to match the Durable Functions v1.x schema. You can find documentation for the v2.x schema here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings?tabs=csharp%2C1x-durable-functions#host-json

I hope this is helpful!

**Comment by vany0114** [comment]
Thanks @cgillum! I'll give it a try.

**Comment by davidmrdavid** [comment]
Thanks @cgillum for the response, and apologies @vany0114 for missing this ticket. I think I missed it when it was first posted and then did not get to your "any updates" message 3 days ago due to BuildConf-prep madness :) . Please do reach out when you've tried Chris' suggestion and let us know if it worked for you. Thanks!

**Comment by vany0114** [comment]
@cgillum it worked, thanks! and sorry for the delayed confirmation but we just made a release yesterday.
