### ISSUE TITLE
No documented way to cancel a sub-orchestrator task?

### ISSUE THREAD

**Issue by joeskeen** [Azure/azure-functions-durable-js#348]
**Describe the bug**

I have a collection of Durable Functions that coordinate a complex workflow. In one orchestrator, I use `callSubOrchestrator` two times to try to solve a problem two different ways. As soon as one comes back using `Task.any()`, I `return`. I would expect that this would immediately return control to the parent orchestrator. But it seems when I inspect the orchestrator status that it is stuck in "Running" status until the other sub-orchestrator completes; only then the parent orchestrator resumes.

Ideally, once one sub-orchestrator returns, I would cancel the other sub-orchestrator, but I can't seem to figure out how to do that. I have looked through the documentation ([here](https://docs.microsoft.com/en-us/javascript/api/durable-functions/task?view=azure-node-latest) and [here](https://docs.microsoft.com/en-us/javascript/api/durable-functions/durableorchestrationcontext?view=azure-node-latest)) and source code and it seems that the [only kind of Task you can cancel is a Timer task](https://github.com/Azure/azure-functions-durable-js/blob/dev/src/task.ts#L104). I'm inside an orchestrator function, and I don't think I can get a [DurableOrchestrationClient](https://docs.microsoft.com/en-us/javascript/api/durable-functions/durableorchestrationclient?view=azure-node-latest) instance from there, so I can't [cancel it that way](https://docs.microsoft.com/en-us/javascript/api/durable-functions/durableorchestrationclient?view=azure-node-latest#durable-functions-durableorchestrationclient-terminate).  I suppose that I could use the HTTP APIs to terminate the orchestration, but I don't know how to get at runtime what the base URL is that I would compute the termination URL from.  Am I missing something obvious, or is there really no way to cancel a Running sub-orchestrator instance from the orchestrator that kicked it off?

**Investigative information**

- Durable Functions extension version: Durable Functions Monitor version v5.3.0
- durable-functions npm module version: `^1.5.4`
- Language (JavaScript/TypeScript) and version: TypeScript `^4.0.0`
- Node.js version: `v14.19.0`

***If deployed to Azure App Service*** : 

N/A as I have been running it locally using Azurite / Durable Functions Monitor

**To Reproduce**

1. Create an orchestrator function (A) that calls a sub-orchestrator function (B)
2. Have orchestrator function B call two sub-orchestrator functions (C, D) but don't `yield` them
3. Call `Task.any()` passing the tasks for sub-orchestrators C and D
4. `yield` the task produced from `Task.any()` 
5. Immediately `return` from orchestrator B as soon as **one** of either C or D complete (but not both)

**Expected behavior**

Orchestrator B is marked as completed as soon as **either** C or D complete

**Actual behavior**

B will still be marked as "Running" until **both** C and D are completed

**Known workarounds**

None that I know of, short of manually terminating the other sub-orchestrator instance via the REST API

**Additional context**

- Development environment VSCode
- Links to source

**Comment by joeskeen** [comment]
OK, I discovered a workaround:

1. Add the following binding to your orchestrator function B (see above):
    ```json
    {
      "name": "starter",
      "type": "orchestrationClient",
      "direction": "in"
    }
    ```
2. In your orchestrator function you can create a Durable Functions client: `const client = df.getClient(context)`
3. When you call sub-orchestrators, you can pass in a custom instance ID. I use orchestrator B's instance ID (you can get using `context.df.instanceId`) and append to the end of it to keep it unique (e.g. ``const cInstanceId = `${context.df.instanceId}-C` ``)
4. When one of the sub-orchestrations complete, you can use `client.terminate(cInstanceId)`. Although you can't `await` this inside of a generator function, that's OK, because you are bailing out and this function won't get called again (like it would if you later do a `yield`)

Despite this working, I do feel that there is a possible documentation gap here. Also, I do worry about the side effects of replaying the function if you have already called the `client.terminate()`... I guess to get around that I could wrap up that part in an Activity and `yield` that instead?

**Comment by davidmrdavid** [comment]
Hi @joeskeen, thank you for reaching out!

You're right in that an orchestrator will not be marked as `Complete` until all of it scheduled work as completed and, as you point out, this can be quite confusing in `Task.WhenAny` scenarios where an orchestrator can reach its `return` statement much earlier than it can receive results for all its tasks. 

We're aware of this being often a counter-intuitive notion for users, but at the moment we cannot change this behavior without introducing a breaking change. When planning for our next major version release in the Durable Functions Extension (the component that powers the Durable Functions Node SDK) I will be advocating for addressing this issue.

In the meantime, I do want to note that we document this notion in here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#query-instances . Please scroll down to find the "Note" which reads:

"""
An orchestrator is not marked as Completed until all of its scheduled tasks have finished and the orchestrator has returned. In other words, it is not sufficient for an orchestrator to reach its return statement for it to be marked as Completed. This is particularly relevant for cases where WhenAny is used; those orchestrators often return before all the scheduled tasks have executed.
"""

With respect to cancelling in-flight activities and/or orchestrators, we've certainly had some early conversations about that feature (and related features), as you can see here: https://github.com/Azure/azure-functions-durable-extension/issues/506. At the moment, we do no have explicit plans to support it, but I'm personally interested in it; it's just a matter of finalizing a design as there's clearly user interest in there.

And that all leads me to your workaround. You're right in that it would not be a good idea to include that `terminate` API call in your orchestrator due to replay, as well as the fact that orchestrators should not do any I/O. I do think you can safely wrap the call inside an Activity and that this should probably give you the behavior your want. Please let us know if it does, I'd like to document the workaround if so. 

Please let me know if you need anything else, thanks!
