### ISSUE TITLE
Multiple calls to context.df.Task.all

### ISSUE THREAD

**Issue by eirikb** [Azure/azure-functions-durable-js#36]
When I call `context.df.Task.all` multiple times in same orchestrator the last call will never end.  
The function will never complete.

Example:
```JavaScript
const df = require("durable-functions");

module.exports = df.orchestrator(function* (context) {
  let helloTasks = [
    context.df.callActivity('SayHello'),
    context.df.callActivity('SayHello')
  ];
  yield context.df.Task.all(helloTasks);

  let moreHelloTasks = [
    context.df.callActivity('SayHello'),
    context.df.callActivity('SayHello')
  ];
  yield context.df.Task.all(moreHelloTasks);

  return 'OK';
});
```

If one of the arrays has one element it will complete.

**Comment by kashimiz** [comment]
Thank you for reporting this issue, @eirikb. I've been able to reproduce it and will update here as I investigate.

**Comment by kashimiz** [comment]
A repro of the above code (with A/B/C/D arguments passed to `SayHello`) results in the following event history being passed to the `durable-functions` shim (abridged/enum values subbed with human-readable text for clarity):

```
[
  // orchestrator orchestrator started, execution started
  { "EventId": 0, "EventType": "TaskScheduled", "Name": "SayHello" },  // A
  { "EventId": 1, "EventType": "TaskScheduled", "Name": "SayHello" },  // B
  // orchestrator completed, orchestrator started
  { "EventId": -1, "EventType": "TaskCompleted", "Result": ""Hello A!"", "TaskScheduledId": 0 },
  // orchestrator completed, orchestrator started
  { "EventId": -1, "EventType": "TaskCompleted", "Result": ""Hello B!"", "TaskScheduledId": 1 },
  { "EventId": 3, "EventType": "TaskScheduled", "Name": "SayHello" },  // D
  { "EventId": 2, "EventType": "TaskScheduled", "Name": "SayHello" },  // C
  // orchestrator completed, orchestrator started
  { "EventId": -1, "EventType": "TaskCompleted", "Result": ""Hello C!"", "TaskScheduledId": 2 },
  // orchestrator completed, orchestrator started
  { "EventId": -1, "EventType": "TaskCompleted", "Result": ""Hello C!"", "TaskScheduledId": 2 },
]
```

Issues of note:
- Non-negative EventIds are presented out-of-order.
- Tracing shows the shim incorrectly matches the `callActivity("SayHello", "D")` call to the history event returning ""Hello C!"", likely due to the (incorrect) assumption that the order in which tasks are scheduled === the order of TaskScheduled events in history. Filed as #38 - while it won't affect this scenario, it can affect calls to `context.df.Task.any`.
- The Durable Functions extension keeps appending the ""Hello C!"" event to the end of the history ad infinitum. These repeat entries have identical timestamps. Not sure why this is happening yet; will dig into DurableTask layer.

**Comment by eirikb** [comment]
Nice find, I wouldn't be able to see the relation.
I guess this can be closed then? Or perhaps it should be open until the PR is complete, and the solution can be verified?

**Comment by kashimiz** [comment]
I'm going to leave this open until the PR is complete and I've verified the issue is fixed against the repro.

**Comment by eirikb** [comment]
Hi.
Totally forgot about this. Tested now and it works fine.
Tested in 1.7.1 and 1.8.0, both works.
