### ISSUE TITLE
Orchestrated function hangs/left in "Running" without any errors

### ISSUE THREAD

**Issue by ahwitz** [Azure/azure-functions-durable-js#388]
**Describe the bug**

We have an orchestrated function that:
- Downloads a large GZip'ed JSON file
- Unzips the file
- Processes the JSON and makes various requests to other services based off its contents

Our issue is that execution sometimes randomly stops in the middle of the orchestrated function execution, and no errors are thrown to the parent orchestrator. We've verified this is the case by adding printouts at each ~4MB chunk of the three processes above, and they stop at seemingly random points in the middle.

This seems to be entirely random, and can happen at any point in any file, and sometimes completes without issue for one file on one attempt and then not for another. The files are usually left at "Running" in the orchestration logs and we do not see anything in the queues in Blob Storage.

**Investigative information**

- Durable Functions extension version: (unknown? Node version should accommodate)
- durable-functions npm module version: 2.0.2
- Language (JavaScript/TypeScript) and version: JS
- Node.js version: 16.x

***If deployed to Azure App Service***

- Timeframe issue observed: constantly over the last few weeks
- Function App name: `2022-09-26T13:26:59.921 [Information] Executing (Reason='(null)', Id=9e576a00-a367-4674-835d-911cf2b04ee3)` - hopefullly that's enough per the wiki?
- Function name(s): only function in there
- Region: East US
- Orchestration instance ID(s):
  - e52ecf570a3d4bca891ea373baef6fcb supposedly successful
  - c74a1e6cc10a4d478a69168363bcf46d, 26cc4a714eff406ab4d6542223d3f596, 181e3d89228642ed9cc454180f91700f, d813f300601745eaa84f7a96c2f2591b, 5e4a8ccaed0a47ea901c9e462a2942e1, 36c1e4af252f41c59eb17daf2ad4a0e9, 4283ff71ba6f4847ac8a377c7f37f52a, 81879221f7c64dfcada38bbe18f4442e, 0f2c11b1cb7b48038c3f58ab7afae72b failures. Some of these show up as errors in the trigger invocations list, but without any error information and with log printouts just abandoned mid-stream when more should exist.

**To Reproduce**

No reliable reproduction found yet.

**Expected behavior**
Function completes without abandoning, or prints error when one was encountered.

**Actual behavior**
Function does not complete and seems to hang.

**Screenshots**
Y'all should have access to log printouts.

**Known workarounds**
None.

**Additional context**

- Development environment (ex. Visual Studio): VSCode
- Links to source: Private
- Additional bindings used: Effectively just a single URL passed in
- Function invocation IDs

**Comment by davidmrdavid** [comment]
Hi @ahwitz, thanks for reaching out.

I took a preliminary look at your application. From what I gather, it seems that your Activity invocation seems to be failing about 80% of the time. Each time, it fails with an error that reads "node exited with code 1 (0x1)". I can't quite figure out what would cause this, but this reads to me e as if the "NodeJS worker" crashed. 

I have a few follow-up questions:
* Is there a possibility that your process is running out of memory? I only ask because you mentioned that you're processing a big file.
* Was this working reliably before, or has this never worked? This will help me rule out if you're being affected by some new infrastructure regression
* You seem to have split your instanceIDs by "successful" and "failed". I'm not 100% sure of what this means, I thought from the title that all these orchestrators were labeled as "Running". Can you please clarify how you're making this grouping? Thanks!

FYI @hossam-nasr. I'll need your NodeJS worker expertise in here.

**Comment by ahwitz** [comment]
Turns out it was actually Node quietly running out of memory, and we were able to reproduce it after setting aside a similarly large VM. I've still got complaints about how logging works, but we pivoted to a VM-only solution for this work since it was far easier to manage than Functions for a variety of reasons. Thanks, regardless.
