### ISSUE TITLE
Unhelpful error message when orchestration not found.

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-durable-js#53]
I was following the sample [on the docs site](https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-js-vscode) but received the following error when hitting the URL for `httpStart`:

```
System.Private.CoreLib: Exception while executing function: Functions.HttpStart. System.Private.CoreLib: Result: Failure
Exception: Error: [object Object]
Stack: Error: [object Object]
    at DurableOrchestrationClient.<anonymous> (C:\_Projects\tmp03\node_modules\durable-functions\lib\src\durableorchestrationclient.js:247:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\_Projects\tmp03\node_modules\durable-functions\lib\src\durableorchestrationclient.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7).
```

I then cloned the project repo (b1512bf7b365b4ff72046934cc9c008c042aff08, current `dev` HEAD) to try the samples and received the same error. I've attached the log file from the function run: [logs.txt](https://github.com/Azure/azure-functions-durable-js/files/2929384/logs.txt). Not quite sure where to go next in diagnosis of the problem, but happy to help.

## Environment

* OS: Windows 10
* `node -v`: 10.15.2
* `func -v`: 2.4.419

**Comment by kashimiz** [comment]
Hi @aaronpowell,

Thanks for reporting this issue. It looks like you're calling an orchestrator that doesn't exist. In this situation, the module throws an error; however, it looks like it's not surfaced well to the user.

`HttpStart` isn't an orchestrator, but a "starter" function that uses the `orchestrationClient` binding (see [docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management#start-instances)). It has a custom route of `orchestrators/{functionName}` defined so that any request to an endpoint matching that pattern will cause it to run, and have the value of `functionName` available to it as a parameter. So for example, if you wanted to run the `E1_HelloSequence` orchestrator, you'd call:

`POST http://localhost:7071/orchestrators/E1_HelloSequence`

That said, the error message really isn't helpful. Keeping this issue open and flagging it as an enhancement to change that.

**Comment by aaronpowell** [comment]
Ah, I see, thanks @kashimiz.

All working now, but yes, a better error message would be nice 😄
