### ISSUE TITLE
context.df.Task.all doesn't throw error

### ISSUE THREAD

**Issue by runceel** [Azure/azure-functions-durable-js#66]
I tried following code on durable-functions@1.1.4 and Microsoft.Azure.WebJobs.Extensions.DurableTask 1.8.0.

```
const orchestrator = df.orchestrator(function* (context) {
  try {
    const tasks = [];
    tasks.push(context.df.callActivity("ErrorActivity"));
    tasks.push(context.df.callActivity("ErrorActivity"));
    var results = yield context.df.Task.all(tasks);
  } catch (e) {
    // error handling
  }
}
```

The "ErrorActivity" always throws an Error.
```
import { AzureFunction, Context } from "@azure/functions"
const activityFunction: AzureFunction = async function (context: Context): Promise<string> {
    throw new Error('network error');
};

export default activityFunction;
```

I expected "yield Task.all(tasks)" statement would throw an Error, but it would return a string array that include an error message. 

I guess that I can handle error, checking isFaulted property in the Task class.
But I think that it is not intuitive behavior.

Is this by design?

**Comment by runceel** [comment]
I've created a repository for easy to reproduce the behavior:

https://github.com/runceel/durable-js-task-all-test

**Comment by kashimiz** [comment]
Thank you for reporting this bug, @runceel, and for providing a repro. This isn't by design; `yield context.df.Task.all(tasks)` should act like `Task.WhenAll(tasks)` does in C#. Specifically, where `tasks` is an array of [`Task`](https://github.com/Azure/azure-functions-durable-js/blob/dev/src/task.ts) objects:

- `yield context.df.Task.all(tasks)` should return the results of all `Tasks` in `tasks`
- If one of the members of `tasks` fails, `yield context.df.Tasks.all(tasks)` should throw an exception.
- Once `yield context.df.Task.all(tasks)` is called, each `Task` in `tasks` should reflect the result of that individual async action: whether it is completed, has faulted, its result, any exception thrown if faulted, etc.

**Comment by runceel** [comment]
@kashimiz 
Thank you for checking this.
I'm looking forward to the bug will be fixed.

**Comment by GP4cK** [comment]
Correction on:
> Once yield context.df.Task.all(tasks) is called, each Task in tasks should reflect the result of that individual async action: whether it is completed, has faulted, its result, any exception thrown if faulted, etc.

If one of the tasks throws, each task **may not** reflect the status of that individual async action.
After Task.all, you still need to yield each task to be able to access their result:

```ts
try {
  yield context.df.Task.all(tasks);
} catch (err) {
  // At least one task failed
}

// Here some tasks may still be pending.

for (let task of tasks) {
  try {
    yield task;
    // Do something with task.result
  } catch (err) {
    // Do something with the error
  }
}
```
