### ISSUE TITLE
Improve DurableOrchestrationClient webhook calls.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-durable-js#89]
Currently the orchestration client uses the Durable Functions extension's webhooks to perform various instance management operations such as starting, terminating, and raising events on orchestrations. This approach has certain disadvantages, such as the possibility for webhooks to not yet be initialized by the time axios sends the webhook request when running on a consumption plan (see #86), resulting in a 503 Service Unavailable response.

The webhook call logic can be improved by adding:

- [ ] retry logic on 503 calls
- [ ] a tracing header to improve logging, such as [here](https://github.com/Azure/azure-functions-host/blob/8cfc7fb6e5d814589eed914e1e690141778244f0/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs#L432)

**Comment by dariagrigoriu** [comment]
@jeffhollan and @kashimiz is this still valid and should this still be a P1?

**Comment by kashimiz** [comment]
@dariagrigoriu I was aware of plans to implement a gRPC channel in the extension, which would remove the need for this work, but am unaware of its current status as Durable JS work has shifted to @ConnorMcMahon . Connor, can you share the current plans for the JS orchestration client?

**Comment by cgillum** [comment]
Adding @anthonychu 

The issue is still valid. Two architectural options are being considered:

1. A new, local gRPC channel managed by the extension
2. A local HTTP channel using the loopback address and existing HTTP webhook code.

Unfortunately we don't have the resources to deliver this in the next couple months. I'm fine with removing the P1 label if it's making issue tracking more complicated.

**Comment by anthonychu** [comment]
With the gRPC and local HTTP options, the worker will be calling the host running on localhost. Is there still a possibility of 503s (host and worker initialized and processing requests before webhooks are ready)?

If we're using this issue to track the work to change the call to a local channel with the 2 options Chris listed, I think we should keep it as a P1 because of potentially significant issues:

* Current method doesn't work with Easy Auth enabled
* Testing found some issues with timeouts related to these webhook calls that may be related to port exhaustion (unsure if switching to a localhost call would fix this, however)
