### ISSUE TITLE
Exception thrown when passing large input to Orchestrator function

### ISSUE THREAD

**Issue by CastleArg** [Azure/azure-functions-durable-js#93]
**Describe the bug**
A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

**Investigative information**

- Durable Functions extension version: 1.8.1
- Function App version (2.0):
- Programming language used: JS

***If JavaScript***

- durable-functions npm module version:
"^1.2.2"

**To Reproduce**

1. create large object (presumably >10485760bytes)
2. Pass it to an orchestrator function
await client.startNew(
    'MyOrchestratorFunction',,
    undefined,
    myLargeObject
  );

**Expected behavior**
Can hit breakpoint at start of Orchestrator function and see my input

**Actual behavior**
vague error message in terminal
Executed 'Functions.MyFunc' (Failed, Id=ea7ccb06-aad7-49ee-8d37-bb48ba6a771d)
[21/06/2019 8:32:43 AM] System.Private.CoreLib: Exception while executing function: Functions.MyFunc. System.Private.CoreLib: Result: Failure
Exception: Error
Stack: Error
    at DurableOrchestrationClient.<anonymous> (c:\dev\MyFunc\node_modules\durable-functions\lib\src\durableorchestrationclient.js:291:23)
    at Generator.throw (<anonymous>)
    at rejected (c:\dev\MyFunc\node_modules\durable-functions\lib\src\durableorchestrationclient.js:5:65).

Putting a breakpoint in catch block of durableorchestrationclient.js startnew() reveals the real error and why not logged:
message.error is null.  Inspecting message itself reveals:

"Request body larger than maxBodyLength limit"
This appears to be from axios default maxBodyLength limit when trying to post to durable task for status inspection.  

Possibly related to https://github.com/Azure/azure-functions-durable-extension/issues/665
part of general problems using Azure Functions for large processing tasks.

**Comment by kashimiz** [comment]
Lifted the `maxContentLength` limit in axios from 10MB to `Infinity`. However, the Functions host still imposes [its own content length limitation of 100 MB. ](https://github.com/Azure/azure-functions-host/blob/7ff14e1bb23f4a77e0499273d57b9b01bef77b5b/src/WebJobs.Script.WebHost/web.config#L19)

A further improvement would be to change the DurableOrchestrationClient implementation to use gRPC rather than the extension webhooks, an improvement we were already considering for the future. However, the gRPC channel has its own message size limit (@mhoeger to confirm.) To get around the gRPC's size limit, the data could be written to a temporary file on the host, and the filepath communicated back to the Durable extension, which would retrieve the data. This would require changes on the extension side, however.

@CastleArg , a suggested workaround is to store your data in blob storage, pass the blob endpoint to the orchestrator, then retrieve the data in an activity function. This may actually be more efficient.

**Comment by mhoeger** [comment]
the gRPC max message length is [135 MB](https://github.com/Azure/azure-functions-host/blob/4fbd99486ca52148dafbe52dceb122602863533b/src/WebJobs.Script.Grpc/Server/GrpcServer.cs#L17), although in practice, the http content size limit to get passed through the gRPC channel is lower then that.
